import { Phenomenon } from '../types';

export const phenomena: Phenomenon[] = [
  {
    id: 'black-holes',
    title: 'Black Holes',
    shortDescription: 'Explore the most mysterious objects in the universe',
    description: 'Black holes are regions of spacetime where gravity is so strong that nothing can escape, not even light.',
    sections: [
      {
        title: 'Event Horizon',
        content: 'The boundary marking the point of no return around a black hole.',
      },
      {
        title: 'Singularity',
        content: 'The infinitely dense point at the center of a black hole.',
      },
      {
        title: 'Hawking Radiation',
        content: 'Theoretical radiation emitted by black holes due to quantum effects.',
      },
    ],
    links: [
      {
        title: 'NASA Black Holes Guide',
        url: 'https://science.nasa.gov/astrophysics/focus-areas/black-holes',
      },
    ],
    isFeatured: true,
    image: "./black_hole.jpg"
  },
  {
    id: 'neutron-stars',
    title: 'Neutron Stars',
    shortDescription: 'Dense stellar remnants with extreme properties',
    description: 'Neutron stars are the collapsed cores of massive stars, containing a mass greater than our Sun in a sphere only about 20 kilometers in diameter.',
    sections: [
      {
        title: 'Formation',
        content: 'Created in the aftermath of a massive supernova explosion.',
      },
      {
        title: 'Properties',
        content: 'Incredibly dense, with powerful magnetic fields and rapid rotation.',
      },
    ],
    links: [
      {
        title: 'ESA Neutron Stars',
        url: 'https://www.esa.int/Science_Exploration/Space_Science/Neutron_stars',
      },
    ],
    isFeatured: true,
    image: "./neutron_star.jpg"
  },
  {
    id: 'gamma-ray-bursts',
    title: 'Gamma-Ray Bursts (GRBs)',
    shortDescription: 'The most energetic explosions in the universe',
    description: 'Gamma-ray bursts are extremely energetic explosions that have been observed in distant galaxies, releasing more energy in seconds than our Sun will emit in its entire lifetime.',
    sections: [
      {
        title: 'Short GRBs',
        content: 'Brief bursts likely caused by neutron star mergers.',
      },
      {
        title: 'Long GRBs',
        content: 'Extended bursts associated with supernovae and massive star collapse.',
      }
    ],
    links: [
      {
        title: 'NASA GRB Overview',
        url: 'https://www.nasa.gov/mission_pages/swift/bursts/index.html',
      }
    ],
    isFeatured: false,
    image: "./gamma_ray_burst.jpg"
  },
  {
    id: 'gravitational-waves',
    title: 'Gravitational Waves',
    shortDescription: 'Ripples in the fabric of spacetime',
    description: 'Gravitational waves are disturbances in the curvature of spacetime caused by accelerated masses that propagate as waves outward from their source.',
    sections: [
      {
        title: 'Detection',
        content: 'First directly observed by LIGO in 2015, confirming Einstein\'s predictions.',
      },
      {
        title: 'Sources',
        content: 'Generated by cosmic events like black hole mergers and neutron star collisions.',
      }
    ],
    links: [
      {
        title: 'LIGO',
        url: 'https://www.ligo.caltech.edu/',
      }
    ],
    isFeatured: false,
    image: "./gravitational_waves.jpg"
  },
  {
    id: 'dark-matter-and-dark-energy',
    title: 'Dark Matter and Dark Energy',
    shortDescription: 'The invisible forces shaping our universe',
    description: 'Dark matter and dark energy make up approximately 95% of the universe, yet remain largely mysterious. Dark matter holds galaxies together, while dark energy drives the universe\'s acceleration.',
    sections: [
      {
        title: 'Dark Matter',
        content: 'Invisible matter that interacts through gravity but not with light.',
      },
      {
        title: 'Dark Energy',
        content: 'The unknown force causing the universe\'s accelerating expansion.',
      }
    ],
    links: [
      {
        title: 'CERN Dark Matter',
        url: 'https://home.cern/science/physics/dark-matter',
      }
    ],
    isFeatured: false,
    image: "./dark_matter.webp"
  },
  {
    id: 'quantum-entanglement',
    title: 'Quantum Entanglement and Wormholes',
    shortDescription: 'Spooky action at a distance',
    description: 'The mysterious quantum connection between particles and its potential relationship to spacetime shortcuts through wormholes.',
    sections: [
      {
        title: 'Entanglement',
        content: 'Quantum correlation between separated particles.',
      },
      {
        title: 'Wormholes',
        content: 'Theoretical tunnels through spacetime.',
      }
    ],
    links: [
      {
        title: 'Quantum Frontiers',
        url: 'https://quantumfrontiers.com/',
      }
    ],
    isFeatured: false,
    image: "./quantum_entanglement.jpg"
  },
  {
    id: 'antimatter-worlds',
    title: 'Antimatter Worlds',
    shortDescription: 'Mirror universe of opposite charge',
    description: 'Theoretical regions of space dominated by antimatter, with implications for cosmology and particle physics.',
    sections: [
      {
        title: 'Properties',
        content: 'Characteristics of antimatter and its interaction with normal matter.',
      },
      {
        title: 'Detection',
        content: 'Methods for identifying antimatter in the universe.',
      }
    ],
    links: [
      {
        title: 'CERN Antimatter',
        url: 'https://home.cern/science/physics/antimatter',
      }
    ],
    isFeatured: false,
    image: "./antimatter.jpg"
  },
  {
    id: 'spacetime-crystals',
    title: 'Space-Time Crystals',
    shortDescription: 'Matter that loops in time',
    description: 'Exotic states of matter that exhibit periodic structure in time as well as space.',
    sections: [
      {
        title: 'Properties',
        content: 'Unique characteristics of temporal crystalline structures.',
      },
      {
        title: 'Applications',
        content: 'Potential uses in quantum computing and precision timing.',
      }
    ],
    links: [
      {
        title: 'Nature: Time Crystals',
        url: 'https://www.nature.com/articles/nature21413',
      }
    ],
    isFeatured: false,
    image: "./spacetime_crystals.png"
  }
];